### ISSUE TITLE
Outreach Assessment

### ISSUE THREAD

**Issue by fifedog** [fifedog/hartOfFolsom#17]
"As an outreach volunteer: 

I want to talk with clients out in the area and ask them some questions to assest their state so we can create connections and be able to track the homeless population to use the data to write grants and get other type of resources.

When I talk with a client I can tap the HART Salesforce app icon on my mobile device and only the contact, activity, and survey question forms will be visible.

When I talk with a client and the mobile device is online I can seach the system and see if they are already in the system. If so then the current assessment will be brought up and an activity will be logged. If the client is not in the system I can enter the contact information and answers to the outreach survey questions.

When I talk with a client and the mobile device is offline I can enter and capture the contact information and answers to the outreach survey questions for upload when the mobile device is online.

When I talk with a client I want to take a photo and upload the photo to the clients contact record.

As a HART administrator I want to review the outreach survey:

- to determine what services a client may need.
- to determine what paperwork they need help with to obtain ID, Social Security card, etc.
- to assign a mentor where appropriate to use the data for grant requests"

**Comment by fifedog** [comment]
Meeting notes: Continuing the flow screen build.

**Comment by fifedog** [comment]
Pete will move the object to UAT while Rich continues with the flow. 
Outreach App is also in the Dev box but will be left in the dev box.

**Comment by fifedog** [comment]
@rsharley - In looking at the outreach object we need to make some changes.

1. Name field. Change this to an auto-number. Format OA-000
2. First name Last name: Remove. We don't need these since this is related to a contact.

**Comment by fifedog** [comment]
@rsharley - Please add Hispanic in the Race

1. Re-order the related list on the contact: Relationships, (moved Team Participation, Outreach assessment to top),  Engage plans, Activities, move Org Affiliations, contact history to bottom

**Comment by fifedog** [comment]
@rsharley In reviewing with Ed:
- Feedback1: On the Flow where we put in the date, would like to have the format when typing in be M-DD-yyyy instead of this (MMM-dd-yyyy): https://www.screencast.com/t/uwdk8PBb
- Feedback2: Please make the Mailing State default to be NULL or '--Picke a value --'

**Comment by rsharley** [comment]
Successfully deployed 5/10/2020 9:22 pm
