### ISSUE TITLE
Salesforce for Volunteers Update - March 1, 2020

### ISSUE THREAD

**Issue by rsharley** [fifedog/hartOfFolsom#23]
Reminder that Guest User Access to Sites for Volunteers for Salesforce (V4S) will end on February 29: UPDATE REQUIRED

 

**Important update for nonprofit organizations currently using Volunteers for Salesforce**

 

What is the change?

Salesforce Sites currently allows nonprofits using V4S to allow people (or a “guest” to your organization) to tell you they want to be a volunteer or to actually sign up for a specific job (and shift). However, as announced in the Power of Us Hub last fall, your V4S Site page will no longer be able to access or display volunteer jobs and shifts. This change will prevent your volunteers from being able to sign-up or access their volunteer data. Fear not; with the latest V4S release we’ve got you covered! 

 

Are you using V4S Sites or have it embedded on your organization’s website?

If so, you need to take action by February 29, 2020 to be in compliance with the improved security measures introduced in the Salesforce Winter ’20 release and maintain the ability for volunteers to sign up for jobs and/or shifts and view their personal volunteering data.  

 

To avoid guests losing access to Sites (perform in Sandbox before executing in production) follow these instructions:

 

Confirm you have the latest version of Volunteers for Salesforce (V4S) 
Go to the Setup menu 
Search for Installed Packages
Locate Volunteers for Salesforce
Check the version number
  * If you are using version 3.113 or earlier, you need to upgrade to the latest V4S version.

 

Enable the Secure Guest User Record Access setting (Winter ’20 Release)
Go to the Setup menu 
Enter Sharing Settings in the Quick Find box
Select Sharing Settings 
Select Secure guest user record access
    * New Salesforce customers automatically have this setting enabled. You can learn more about this setting on Salesforce Help.

 

Grant Guest User Update Access
Go to the Setup menu
Search for Custom Settings
Click Volunteers Settings
Click Manage. (If Custom Settings have not been set, click New. If Custom Settings have been set, click Edit.)
Select Grant Guest User Update Access
Click Save
 

Create Criteria Based Sharing Rules.
For detailed instructions on setting up these Criteria Based Sharing Rules, go to Define Sharing Rules.
 

To find out more details about this change visit Volunteers for Salesforce Site Guest User FAQ.

**Comment by fifedog** [comment]
updated in UAT; But since we don't have the application running on the website can't really test the features.

**Comment by fifedog** [comment]
Updated production custom settings, and Sharing. Don't know what sharing rules to create

**Comment by fifedog** [comment]
I've verified the settings are updated in production. Unsure why I moved this back out of closed before.
