### ISSUE TITLE
Lead convert: Areas of interest

### ISSUE THREAD

**Issue by fifedog** [fifedog/hartOfFolsom#25]
Upon lead convert there is an error.

**Comment by rsharley** [comment]
The Areas of Interest multi-picklist field in the Contact and Lead objects did not match. Ed requested the Lead object Areas of Interest field be modified to have the same multi-field picklist value set as the Contact object. I made the change to the Lead object and also removed the restriction on the Contact object that restricts the picklist to the values defined in the value set. An email was sent informing Ed of the change and asking him to test converting a lead (volunteer) to a contact and to let me know the results.
